### ISSUE TITLE
Rubric

### ISSUE THREAD

**Issue by digitalsara** [digitalsara/portfolio#1]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & sections** | Barely started | Missing lots of sections/pages | Has most of the sections/pages, some missing | All sections/pages exist and are well done |
| **Personality** | Bland, boring, just another graphic designer | Fairly generic but may be better with visual design | Quality layouts and unique, personable content | Unique and recognizable as you, with engaging, personable content |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | Real content, well written, no grammar or spelling errors |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | Looks great on all screen sizes |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | Well indented, fully valid, good semantics |

**Comment by KseniaZhe** [comment]
Pages & sections: 3 points. The home page and one porfolio piece page are well done.
Personality: 3 points. Unique and recognizable as you, with engaging, personable content.
Text content: 3 points. Real content, well written, no grammar or spelling errors
Responsiveness: 3 points. Looks great on all screen sizes.
Code quality: 3 points. Used classes and groups. awesome.

**Comment by catherine9** [comment]
Pages & sections: Home page is nicely done, 3 points.
Personality: Gets straight to the point simple and unique, defiantly shows it is Sara Habel, 3 points
Text content: Content is nicely placed, love the font choice 3 points
Responsiveness: Very Responsive, nothing is touching when at 320px, 3points
Code Quality: straight forward, not too complicated 3 points

**Comment by planetorium** [comment]
| | 0 points | 1 points | 2 points | 3 points |
| --- | --- | --- | --- | --- |
| **Pages & sections** | Barely started | Missing lots of sections/pages | Has most of the sections/pages, some missing | **All sections/pages exist and are well done** |
| **Personality** | Bland, boring, just another graphic designer | Fairly generic but may be better with visual design | Quality layouts and unique, personable content | **Unique and recognizable as you, with engaging, personable content** |
| **Text content** | Fake content only | Some real content, some fake | All real content but with lots of errors | **Real content, well written, no grammar or spelling errors** |
| **Responsiveness** | Not responsive | Works on some screens | Responsive but with lots of awkwardness | **Looks great on all screen sizes** |
| **Code quality** | Barely started | Indentation is barely existent, lots of validation errors, very poor semantics | Decent indentation, just a couple validation errors, decent semantics | **Well indented, fully valid, good semantics** |
