### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by sungwoonjeong** [digitalsara/portfolio#9]
your button for 'About me' cuts off at 320px(screen size)

**Comment by digitalsara** [comment]
Hey @sungwoonjeong, which page and section are you seeing this issue? I don't have an "About Me" section

**Comment by sungwoonjeong** [comment]
Sorry i wrote it on wrong issue. Sorry!
Btw your website looks nice

**Comment by digitalsara** [comment]
Ah okay thank you!
